language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4.0"
  - "4.2"
  - "5.0"
  - "5.1"
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_script: "npm run-script coverall"
