language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "latest"
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_script: "npm run-script coverall"
